name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn test:panel

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    concurrency: "run"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@nittaa"
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build App
        run: |
          yarn build:panel
      - name: Copy Readme
        run: |
          yarn cpy:readme
      - name: Publish with yarn
        run: |
          cd packages/trpc-panel
          # GitHub Release タグ名から先頭の 'v' を除いてバージョンを取得
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "publishing @nittaa/trpc-panel@${VERSION}"
          yarn publish --access public --new-version "${VERSION}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
